# ?????
server:
  port: 3000
  servlet:
    context-path: /

# ?????
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sls
    username: root
    password: 12345678

# MyBatis??
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.studentcourse.sms.entity
  configuration:
    map-underscore-to-camel-case: true  # ????????

# ????
logging:
  level:
    com.studentcourse.mapper: DEBUG
    root: INFO